### PR TITLE
Add views to follow/unfollow

### PR DESCRIPTION
**Pull request by ArianaGu**
Add `FollowView` to create/delete follow relationship and search given user's following people.
Also add migration file.
The `backend/graminsta/core/serializers.py` is copied from [add register backend pull request](https://github.com/SPS-2020-Team-15/Graminsta/pull/4) to return JSON format users.

### CODE REVIEW

**Comment by shiyi001** [comment]
It seems that in the `follow` relationship, the UserInfo serializer is not needed.

**Comment by ArianaGu** [comment]
> It seems that in the `follow` relationship, the UserInfo serializer is not needed.

Yes it is not needed! I copied the file all along and put it in the `backend/graminsta/core/` directory, thinking this may be helpful to merge conveniently...?

**Comment by shiyi001** [comment]
> > It seems that in the `follow` relationship, the UserInfo serializer is not needed.
> 
> Yes it is not needed! I copied the file all along and put it in the `backend/graminsta/core/` directory, thinking this may be helpful to merge conveniently...?

Maybe `git pull` command meets your demand?

**Comment by Time1ess** [comment]
Please follow Git workflow.

To start to work on your feature:

1. Switch to `dev` branch
2. Use `git checkout -b <new_branch_name>` to create your branch based on current `dev`.
3. Work on your new branch.
4. Create PR from that branch, and try to merge your changes into `dev`.
5. (If there are any conflicts suggested by Github)
    1. Switch to `dev` branch
    2. Use `git pull` to fetch and merge the latest changes.
    3. Switch to your working branch
    4. Use `git merge dev` to merge the latest changes from dev into your branch.
    5. Use `git push` to push merged results to your PR

**Comment by ArianaGu** [comment]
> Please follow Git workflow.
> 
> To start to work on your feature:
> 
> 1. Switch to `dev` branch
> 2. Use `git checkout -b <new_branch_name>` to create your branch based on current `dev`.
> 3. Work on your new branch.
> 4. Create PR from that branch, and try to merge your changes into `dev`.
> 5. (If there are any conflicts suggested by Github)
>    
>    1. Switch to `dev` branch
>    2. Use `git pull` to fetch and merge the latest changes.
>    3. Switch to your working branch
>    4. Use `git merge dev` to merge the latest changes from dev into your branch.
>    5. Use `git push` to push merged results to your PR

Got it! I modified it to only contain the necessary code now.

**Review by Time1ess — CHANGES_REQUESTED** [review]
Your PR still include changes from others' PR, if you are not able to revert those changes. Please consider create another PR.

**Pull request closed without merging**
